version: "3"

services:
  web:
    environment:
      - CYPRESS_VIDEO=false
    build:
      context: .
      dockerfile: Dockerfile.github-actions

    command: bash -c "yarn build && yarn test"

    volumes:
      # make sure these line up with $APP_DIR
      - gh_node_modules:${GITHUB_WORKSPACE}/node_modules
      - .:${GITHUB_WORKSPACE}

    ports:
      - "4000:4000"
      - "8080:8080"
volumes:
  gh_node_modules:
