version: "3"

services:
  web:
    environment:
      - CYPRESS_VIDEO=false
    build:
      context: .
      dockerfile: Dockerfile.github-actions
    command: bash -c "yarn build && yarn test"

    volumes:
      # make sure these line up with $APP_DIR
      - .:/app
      - node_modules:/app/node_modules

    depends_on:
      - e2e

    ports:
      - "4000:4000"
      - "8080:8080"
volumes:
  node_modules:
