version: "3"

services:
  web:
    environment:
      - CYPRESS_VIDEO=false
    build:
      context: .

    command: bash -c "yarn build && yarn test"

    volumes:
      # make sure these line up with $APP_DIR
      - node_modules:${APP_DIR:-/home/user/app}/node_modules
      - cypress:/home/node/.cache/Cypress
      - .:${APP_DIR:-/home/user/app}

    ports:
      - "4000:4000"
      - "8080:8080"
volumes:
  node_modules:
  cypress:
