name: build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker-compose build -f docker-compose.github-actions.yml
      - name: Lint files and build pkg
        run: |
          docker-compose run --rm web bash -c "yarn lint && yarn build"
      - name: Test files
        run: |
          docker-compose run --rm web yarn test:ci
