name: build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker-compose -f docker-compose.github-actions.yml build
      - name: Lint files and build pkg
        run: |
          docker-compose -f docker-compose.github-actions.yml run --rm web bash -c "yarn lint && yarn build && yarn install --force"
      - name: Test files
        run: |
          docker-compose -f docker-compose.github-actions.yml run --rm web yarn test
