name: unit-tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 15
    name: Node ${{ matrix.node_version }} - on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn install
      - run: "yarn test:unit"

  e2e-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 15
    name: Node ${{ matrix.node_version }} - on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: "yarn install && yarn build && cd __tests__/examples/example_dir && yarn install"
      - run: "yarn test:unit"
